### ISSUE TITLE
View error message

### ISSUE THREAD

**Issue by celsoandrade** [warmans/silex-ldap-auth-controller-provider#1]
Trying to access /auth/login I'm getting this error message.

Identifier "view" is not defined.

**Comment by warmans** [comment]
Do you have any other existing views? i.e. is there a view service in your container?

**Comment by celsoandrade** [comment]
I have this in my index.php

``` php
$app->register(new Silex\Provider\TwigServiceProvider(), array(
    'twig.path' => __DIR__ . '/../views',
    'twig.options' => array('cache' => __DIR__ . '/../cache'),
));
```

All my twig templates are in /views.
I did a simple test here and replace the line 67 to this:

``` php
    return $app['twig']->render('auth/login.html.twig');
```

Now I can see login page but I know its just a hack.

How can I solve this?

Thank you

**Comment by warmans** [comment]
I'm honestly not sure. Twig only registers a "twig" service whereas the php-view engine registers one called "view". Presumably other view engines do things differently too. I don't know if it will just need to check for the different methods: 

```
$view = $app['twig'] ?: $app['view']
$view->render...
```

or possibly define another config option called like auth.view.service=twig then 

```
$app[$app['auth.view.service']]->render....
```

Any better ideas?

**Comment by celsoandrade** [comment]
Also I use:

``` php
"twig/twig": "^1.18",
"symfony/twig-bridge": "^2.6",
```

**Comment by celsoandrade** [comment]
Thank you for your help.

For now I'll use like this:

$app['twig'] instead of $app['view']

Later I'll refactory and maybe try a PR if is possible.
